# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/dnn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/dnn.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n easy_rec/python/protos/dnn.proto\x12\x06protos\"h\n\x03\x44NN\x12\x14\n\x0chidden_units\x18\x01 \x03(\r\x12\x15\n\rdropout_ratio\x18\x02 \x03(\x02\x12\x1e\n\nactivation\x18\x03 \x01(\t:\ntf.nn.relu\x12\x14\n\x06use_bn\x18\x04 \x01(\x08:\x04true')
)




_DNN = _descriptor.Descriptor(
  name='DNN',
  full_name='protos.DNN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hidden_units', full_name='protos.DNN.hidden_units', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropout_ratio', full_name='protos.DNN.dropout_ratio', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activation', full_name='protos.DNN.activation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("tf.nn.relu").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_bn', full_name='protos.DNN.use_bn', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['DNN'] = _DNN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DNN = _reflection.GeneratedProtocolMessageType('DNN', (_message.Message,), dict(
  DESCRIPTOR = _DNN,
  __module__ = 'easy_rec.python.protos.dnn_pb2'
  # @@protoc_insertion_point(class_scope:protos.DNN)
  ))
_sym_db.RegisterMessage(DNN)


# @@protoc_insertion_point(module_scope)
