# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/fm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/fm.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n\x1f\x65\x61sy_rec/python/protos/fm.proto\x12\x06protos\"\'\n\x02\x46M\x12!\n\x11l2_regularization\x18\x05 \x01(\x02:\x06\x30.0001')
)




_FM = _descriptor.Descriptor(
  name='FM',
  full_name='protos.FM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.FM.l2_regularization', index=0,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.0001),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['FM'] = _FM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FM = _reflection.GeneratedProtocolMessageType('FM', (_message.Message,), dict(
  DESCRIPTOR = _FM,
  __module__ = 'easy_rec.python.protos.fm_pb2'
  # @@protoc_insertion_point(class_scope:protos.FM)
  ))
_sym_db.RegisterMessage(FM)


# @@protoc_insertion_point(module_scope)
